---

kind: pipeline
name: default
type: docker

platform:
  arch: amd64
  os: linux

steps:

  - name: update-ABI-docs
    image: docker.pkg.github.com/vegaprotocol/devops-infra/cipipeline-frontend:13
    pull: always
    volumes: []
    environment: {}
    depends_on: []
    commands:
      - if echo "$$DRONE_COMMIT_MESSAGE" | grep -qF '[NOCI]' ; then echo "Skipping CI" ; exit 0 ; fi
      - bash -xe ./.build-abi-doc.sh
      - git diff --name-only | grep '/README.md$$' || exit 0
      - umask 0077
      - mkdir -p ~/.ssh
      - ssh-keyscan github.com 1>~/.ssh/known_hosts 2>/dev/null
      - git diff --name-only | grep '/README$$' | xargs -r git commit -m 'Update ABI documentation [NOCI]'
      - git push origin "$DRONE_BRANCH"
    when:
      event:
        - push
      ref:
        - refs/heads/**

volumes: []

image_pull_secrets:
  - dockerconfig
